class FacebooksController < ApplicationController
  before_filter :require_authentication, :only => :destroy

  # handle Facebook Auth Cookie generated by JavaScript SDK
  def show
    #logger.info "SHOW"
    auth = Facebook.auth.from_cookie(cookies)
    authenticate Facebook.identify(auth.user)
    redirect_to Facebook.config[:app_url]
  end

  # handle Normal OAuth flow: start
  def new
    #logger.info "NEW"
    @auth_url = Facebook.auth.client.web_server.authorize_url(
        :redirect_uri => Facebook.config[:app_url] << "facebook/callback",
        :scope => Facebook.config[:perms]
      )
  end

  # handle Normal OAuth flow: callback
  def create
    #logger.info "CREATE"
    access_token = Facebook.auth.client.web_server.get_access_token(
      params[:code],
      :redirect_uri => Facebook.config[:app_url] << "facebook/callback"
    )
    user = FbGraph::User.me(access_token).fetch
    authenticate Facebook.identify(user)
    redirect_to me_url
  end

  def destroy
    unauthenticate
    redirect_to root_url
  end

end